export default Object.freeze({ 
    TOP_ACCESSORY: 13,
    ARMOR: 12,
    HELMET: 11,
    HOOD: 10,
    HAT_HOOD: 9,
    HAT: 8,
    FULL_MASK: 7,
    UPPER_MASK: 6,
    LOWER_MASK: 5,
    SHOULDER: 4,
    CLOTH: 3,
    HAIR: 2,
    SKIN: 1,
    BASE: 0,
})
